blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/tubekinan/SMSpam/discussions
    about: Please ask and answer questions here.
  - name: Email Contact
    url: https://github.com/tubekinan
    about: For direct contact with the maintainer.
